module:
  hugoVersion:
    min: "0.82.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-media
  - source: tnd-imgix
    target: layouts/partials/tnd-imgix
  - source: console
    target: layouts/partials/tnd-media
  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-imgix